"""
Database observer for persisting messages during streaming.
"""

import json
import uuid
from datetime import datetime, timezone

from langchain_core.messages import AIMessage, BaseMessage, ToolMessage

from app.domain import Message, MessageRole, ToolCall
from app.domain.repositories import ThreadRepository
from app.domain.repositories import MessageRepository


class DatabaseObserver:
    """
    Observer that persists AI messages to the database.

    This observer listens to stream events and saves the AI response
    to the database when the stream completes.
    """

    def __init__(
        self,
        message_repository: MessageRepository,
        thread_repository: ThreadRepository,
        thread_id: str,
    ):
        """
        Initialize the database observer.

        Args:
            message_repository: Repository for message persistence
            thread_id: ID of the conversation thread
        """
        self.message_repository = message_repository
        self.thread_repository = thread_repository
        self.thread_id = thread_id
        self._saved_tool_call_ids: set[str] = set()
        self._saved_ai_signatures: set[str] = set()

    async def on_event(self, event) -> None:
        """
        Called when a stream event is processed.

        No-op for persistence. Tool results must be persisted only from
        LangChain ToolMessage objects on node completion so tool_call_id
        stays aligned with assistant tool_calls.

        Args:
            event: The stream event that was processed
        """
        return

    async def _persist_active_build_id(self, content: str) -> None:
        try:
            parsed = json.loads(content)
        except Exception:
            return
        if not isinstance(parsed, dict):
            return
        tool_name = parsed.get("tool")
        if tool_name != "build_lookup":
            return
        build_id = parsed.get("build_id")
        if not isinstance(build_id, str) or not build_id.strip():
            return
        await self.thread_repository.set_active_build_id(self.thread_id, build_id)

    async def on_node_complete(self, node: str, messages: list[BaseMessage]) -> None:
        """
        Called when a node completes and produces new messages.

        Persists AI and tool messages generated by the graph.

        Args:
            node: The node name that completed
            messages: New messages produced by the node
        """
        for message in messages:
            if isinstance(message, AIMessage):
                signature = self._build_ai_signature(message)
                if signature in self._saved_ai_signatures:
                    continue
                self._saved_ai_signatures.add(signature)

            if isinstance(message, ToolMessage) and message.tool_call_id:
                tool_call_id = message.tool_call_id
                if tool_call_id in self._saved_tool_call_ids:
                    continue
                self._saved_tool_call_ids.add(tool_call_id)
                domain_message = self._convert_message(message)
                if domain_message is not None:
                    try:
                        await self.message_repository.save(domain_message)
                        await self._persist_active_build_id(
                            content=domain_message.tool_result or domain_message.content
                        )
                    except Exception:
                        self._saved_tool_call_ids.discard(tool_call_id)
                        raise
                continue

            domain_message = self._convert_message(message)
            if domain_message is not None:
                await self.message_repository.save(domain_message)

    def _build_ai_signature(self, message: AIMessage) -> str:
        payload = {
            "content": message.content or "",
            "tool_calls": message.tool_calls or [],
        }
        return json.dumps(payload, sort_keys=True, ensure_ascii=True)

    async def on_stream_complete(self, full_response: str) -> None:
        """
        Called when the stream is complete.

        Saves the AI response to the database.

        Args:
            full_response: The complete accumulated response text
        """
        # Persistence now happens on node completion.
        # We keep this method as a no-op for future extensions.
        return

    async def on_error(self, error: Exception) -> None:
        """
        Called when an error occurs during streaming.

        Could be extended to log errors or save partial responses.

        Args:
            error: The exception that occurred
        """
        # Could log the error or save partial response
        pass

    def _convert_message(self, message: BaseMessage) -> Message | None:
        """
        Convert a LangChain BaseMessage to a domain Message.

        Args:
            message: LangChain message instance

        Returns:
            Domain Message or None if not supported
        """
        if isinstance(message, AIMessage):
            return self._convert_ai_message(message)

        if isinstance(message, ToolMessage):
            return self._convert_tool_message(message)

        return None

    def _convert_ai_message(self, message: AIMessage) -> Message:
        """Convert AIMessage to domain Message (including tool calls)."""
        tool_calls = None
        if message.tool_calls:
            tool_calls = [
                ToolCall(
                    id=tool_call.get("id", ""),
                    name=tool_call.get("name", ""),
                    arguments=json.dumps(tool_call.get("args", {})),
                )
                for tool_call in message.tool_calls
            ]

        return Message(
            id=str(uuid.uuid4()),
            thread_id=self.thread_id,
            role=MessageRole.AI,
            content=message.content or "",
            timestamp=datetime.now(timezone.utc),
            tool_calls=tool_calls,
        )

    def _convert_tool_message(self, message: ToolMessage) -> Message:
        """Convert ToolMessage to domain Message."""
        return Message(
            id=f"tool-{message.tool_call_id}"
            if message.tool_call_id
            else str(uuid.uuid4()),
            thread_id=self.thread_id,
            role=MessageRole.TOOL,
            content=message.content or "",
            timestamp=datetime.now(timezone.utc),
            tool_call_id=message.tool_call_id,
            tool_result=message.content or "",
        )
