"""
Database observer for persisting messages during streaming.
"""

import json
import logging
import uuid
from datetime import datetime, timezone

from langchain_core.messages import BaseMessage

from app.domain import Message, MessageRole, ToolCall
from app.domain.repositories import ThreadRepository
from app.domain.repositories import MessageRepository

logger = logging.getLogger(__name__)


class DatabaseObserver:
    """
    Observer that persists AI/tool messages from normalized stream events.
    """

    def __init__(
        self,
        message_repository: MessageRepository,
        thread_repository: ThreadRepository,
        thread_id: str,
    ):
        """
        Initialize the database observer.

        Args:
            message_repository: Repository for message persistence
            thread_id: ID of the conversation thread
        """
        self.message_repository = message_repository
        self.thread_repository = thread_repository
        self.thread_id = thread_id
        self._saved_tool_call_ids: set[str] = set()
        self._saved_ai_runs: set[str] = set()

    async def on_event(self, event) -> None:
        """
        Called when a stream event is processed.

        Persists normalized internal events emitted by PersistenceFacade.

        Args:
            event: The stream event that was processed
        """
        if event.event == "persist_ai_message":
            await self._handle_ai_persistence_event(event.data)
            return
        if event.event == "persist_tool_message":
            await self._handle_tool_persistence_event(event.data)
            return
        return

    async def _persist_active_build_id(self, content: str) -> None:
        try:
            parsed = json.loads(content)
        except Exception:
            return
        if not isinstance(parsed, dict):
            return
        tool_name = parsed.get("tool")
        if tool_name != "build_lookup":
            return
        build_id = parsed.get("build_id")
        if not isinstance(build_id, str) or not build_id.strip():
            return
        await self.thread_repository.set_active_build_id(self.thread_id, build_id)

    async def on_node_complete(self, node: str, messages: list[BaseMessage]) -> None:
        """
        Called when a node completes and produces new messages.

        Persists AI and tool messages generated by the graph.

        Args:
            node: The node name that completed
            messages: New messages produced by the node
        """
        return

    async def on_stream_complete(self, full_response: str) -> None:
        """
        Called when the stream is complete.

        Args:
            full_response: The complete accumulated response text
        """
        # Persistence happens during event processing.
        return

    async def on_error(self, error: Exception) -> None:
        """
        Called when an error occurs during streaming.

        Could be extended to log errors or save partial responses.

        Args:
            error: The exception that occurred
        """
        # Could log the error or save partial response
        pass

    async def _handle_ai_persistence_event(self, data: dict) -> None:
        run_id = str(data["run_id"])
        if run_id in self._saved_ai_runs:
            return
        self._saved_ai_runs.add(run_id)
        is_partial = bool(data["is_partial"])
        raw_tool_calls = data.get("tool_calls", [])
        tool_calls = self._parse_tool_calls(raw_tool_calls)
        message = Message(
            id=str(uuid.uuid4()),
            thread_id=self.thread_id,
            role=MessageRole.AI,
            content=str(data["content"]),
            timestamp=datetime.now(timezone.utc),
            tool_calls=tool_calls,
            reasoning="partial_stream" if is_partial else None,
        )
        await self.message_repository.save(message)

    async def _handle_tool_persistence_event(self, data: dict) -> None:
        tool_call_id = str(data["tool_call_id"])
        if tool_call_id in self._saved_tool_call_ids:
            return
        self._saved_tool_call_ids.add(tool_call_id)
        output = str(data["output"])
        message = Message(
            id=f"tool-{tool_call_id}",
            thread_id=self.thread_id,
            role=MessageRole.TOOL,
            content=output,
            timestamp=datetime.now(timezone.utc),
            tool_call_id=tool_call_id,
            tool_result=output,
        )
        try:
            await self.message_repository.save(message)
            await self._persist_active_build_id(content=output)
        except Exception:
            self._saved_tool_call_ids.discard(tool_call_id)
            raise

    def _parse_tool_calls(self, raw_tool_calls: object) -> list[ToolCall] | None:
        if not raw_tool_calls:
            return None
        if not isinstance(raw_tool_calls, list):
            raise RuntimeError("DatabaseObserver: tool_calls must be a list")

        tool_calls: list[ToolCall] = []
        for item in raw_tool_calls:
            if not isinstance(item, dict):
                raise RuntimeError("DatabaseObserver: tool_call item must be dict")
            tool_calls.append(
                ToolCall(
                    id=str(item["id"]),
                    name=str(item["name"]),
                    arguments=json.dumps(item.get("args", {})),
                )
            )
        return tool_calls
